services:
  app:
    container_name: "danktodo"
    build:
      context: .
    restart: "always"
    ports:
      - "20260:8080"
    stdin_open: true
    volumes:
      - ./:/opt/danktodo/data
    environment:
      - VERSION=${COMMIT_SHA}
    env_file: .env.docker
